# Generator

函数执行会停在 `yield` 语句之后，等待下一次调用，一般是 `next()`，遇到 `yield` 会再次停止


## 基础

**特点**

可以交出函数的执行权（即暂停执行）


**语法**

函数名之前加 `*`
内部使用 `yield` 语句

**例子**

```js
function *gen() {
    yield 'hello'
    yield 'world'
    return 'ending'
}

const g = gen()

console.log(g.next())
console.log(g.next())
console.log(g.next())
console.log(g.next())

// output:
// { value: 'hello', done: false }
// { value: 'world', done: false }
// { value: 'ending', done: true }
// { value: undefined, done: true }
```

**yield**

遇到 `yield`，就会暂停执行函数后面的操作，并返回 `yield` 后面的表达式的值

**next**

调用 `next` 方法，遍历 Generator 下一个内部状态

**next 传参**

```js
> function *f(){
... for(let i=0; true; i++){
..... let reset = yield i
..... if (reset) {i = -1}
..... }
... }
undefined
> let g = f()
undefined
> g.next()
{ value: 0, done: false }
> g.next()
{ value: 1, done: false }
> g.next()
{ value: 2, done: false }
> g.next()
{ value: 3, done: false }
> g.next(true)
{ value: 0, done: false }
> g.next()
{ value: 1, done: false }
> g.next()
{ value: 2, done: false }
>
```

作用：next 函数将参数注入到 yield 语句的位置。也就是向 Generator 注入值，从而调整函数行为

另一个例子：
```js
> function *foo(x) {
... let y = 2 * (yield (x + 1))
... let z = yield (y / 3)
... return (x + y + z)
... }
undefined
> let a = foo(5)
undefined
> a.next()
{ value: 6, done: false }
> a.next()  // 没有传参，导致 y 的值等于 2 * undefined
{ value: NaN, done: false }
> a.next()
{ value: NaN, done: true }
>
> var b = foo(5)
undefined
> b.next()
{ value: 6, done: false }
> b.next(12)
{ value: 8, done: false }
> b.next(13)
{ value: 42, done: true }
>
```

注意：next 方法的参数表示上一个yield表达式的返回值，所以在第一次使用next方法时，传递参数是无效的


**for ... of**

使用 `for ... of` 可以遍历 Generator

```js
function *foo() {
    yield 1
    yield 2
    yield 3
    yield 4
    yield 5
    yield 6
    return 7
}

for (let v of foo()) {
    console.log(v)
}

// output: 1 2 3 4 5 6
// 没有 7
```

**扩展运算符和解构赋值**

都可以遍历 Generator

```js
function* numbers () {
  yield 1
  yield 2
  return 3
  yield 4
}

// 扩展运算符
[...numbers()] // [1, 2]

// Array.from 方法
Array.from(numbers()) // [1, 2]

// 解构赋值
let [x, y] = numbers();
x // 1
y // 2

// for...of 循环
for (let n of numbers()) {
  console.log(n)
}
// 1
// 2
```

**throw**

Generator 函数返回的遍历器对象，都有一个throw方法，可以在函数体外抛出错误，然后在 Generator 函数体内捕获

```js
let g = function* () {
    try {
        yield
    } catch (e) {
        console.log('内部捕获', e)
    }
}

var i = g()
i.next()

try {
    i.throw('a')  // 被 Generator 内部的 try 捕获
    i.throw('b')  // Generator 内部的 try 已经执行过了，不可以再捕获。所以向上抛出
} catch(e) {
    console.log('外部捕获', e)
}
```

**抛出 Error 对象**

throw方法可以接受一个参数，该参数会被catch语句接收，建议抛出Error对象的实例

```js
let g = function* () {
    try {
        yield
    } catch(e) {
        console.log(e)
    }
}

let i = g()
i.next()
i.throw(new Error('出错了。。'))

```

**return**

Generator 除了 next 方法，还有 return 方法，return 会终止 Generator

```js
function *gen() {
    yield 1
    yield 2
    yield 3
}

let g = gen()

console.log(g.next())  // { value: 1, done: false }
console.log(g.return('foo')) // { value: 'foo', done: true }
console.log(g.next())  // { value: undefined, done: true }
```


注意：如果 Generator 函数内部有try...finally代码块，且正在执行try代码块，那么return()方法会导致立刻进入finally代码块，执行完以后，整个函数才会结束


**yield***


在 Generator 里调用 Generator

```js
function *foo() {
    yield 'a'
    yield 'b'
}

function *bar() {
    yield 'x'
    yield* foo()
    yield 'y'
}

for (let v of bar()) {
    console.log(v)
}

// output: x a b y
```

等价代码

```js
yield* foo()

// 等价于
for (let i of foo()) {
  console.log(i);
}
```

**协程**

如果将 Generator 函数当作协程，完全可以将多个需要互相协作的任务写成 Generator 函数，它们之间使用yield表达式交换控制权
